import { Building2, CalendarDays, LockKeyhole, Mail, MapPin, Phone, RefreshCw, Search, UsersRound } from 'lucide-react';
import { FormEvent, useEffect, useState } from 'react';
import { fetchPrivateDirectorDirectory, refreshPrivateDirectorDirectory } from '../lib/api';

const TOKEN_KEY='cheesebaggers.playerDirectoryAccess';

export default function DirectorDirectoryView(){
  const [token,setToken]=useState(()=>sessionStorage.getItem(TOKEN_KEY)||'');
  const [tokenInput,setTokenInput]=useState(''); const [view,setView]=useState('DIRECTORS');
  const [data,setData]=useState<any>(); const [loading,setLoading]=useState(false); const [refreshing,setRefreshing]=useState(false);
  const [error,setError]=useState(''); const [searchInput,setSearchInput]=useState(''); const [search,setSearch]=useState('');
  const [state,setState]=useState('ALL'); const [dateFrom,setDateFrom]=useState(''); const [dateTo,setDateTo]=useState('');
  const load=()=>{if(!token)return;setLoading(true);setError('');fetchPrivateDirectorDirectory(token,{view,search,state,dateFrom,dateTo,limit:200}).then(setData).catch((e:Error)=>setError(e.message)).finally(()=>setLoading(false))};
  useEffect(load,[token,view,search,state,dateFrom,dateTo]);
  const unlock=(e:FormEvent)=>{e.preventDefault();if(!tokenInput.trim())return;sessionStorage.setItem(TOKEN_KEY,tokenInput.trim());setToken(tokenInput.trim())};
  const apply=(e:FormEvent)=>{e.preventDefault();setSearch(searchInput.trim())};
  const refresh=async()=>{setRefreshing(true);try{await refreshPrivateDirectorDirectory(token);load()}catch(e:any){setError(e.message)}finally{setRefreshing(false)}};
  if(!token)return <section className="mx-auto mt-5 max-w-xl rounded-[30px] border border-amber-300/25 bg-zinc-950 p-7"><LockKeyhole className="text-amber-300" size={34}/><div className="mt-4 text-xs font-black uppercase tracking-[.24em] text-amber-300">Private director directory</div><h2 className="mt-2 text-3xl font-black">Directors, venues and events</h2><p className="mt-3 text-sm leading-6 text-zinc-400">Use the same administrator access code as the player directory.</p><form onSubmit={unlock} className="mt-5 space-y-3"><input type="password" value={tokenInput} onChange={e=>setTokenInput(e.target.value)} placeholder="Directory access code" className="w-full rounded-2xl border border-white/15 bg-zinc-900 p-4 outline-none"/><button className="min-h-[54px] w-full rounded-2xl bg-amber-300 font-black text-black">Open directory</button></form>{error&&<p className="mt-3 text-red-300">{error}</p>}</section>;
  const s=data?.summary||{}; const rows=data?.rows||[];
  return <section className="mt-4 space-y-4">
    <div className="rounded-[30px] border border-white/10 bg-zinc-950 p-5 sm:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:justify-between"><div><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.24em] text-amber-300"><UsersRound size={17}/> Private director directory</div><h2 className="mt-2 text-3xl font-black">Directors, venues and event history</h2><p className="mt-2 text-sm text-zinc-500">Captured ACL event administration records joined to attendance and venue history.</p></div><button onClick={refresh} disabled={refreshing} className="flex min-h-[50px] items-center justify-center gap-2 rounded-2xl border border-amber-300/40 px-4 font-black text-amber-200"><RefreshCw size={17} className={refreshing?'animate-spin':''}/>{refreshing?'Indexing…':'Index captured events'}</button></div>
      <div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-5"><Summary label="Directors" value={s.directors}/><Summary label="Venues" value={s.venues}/><Summary label="Events" value={s.events}/><Summary label="Avg players/event" value={s.average_players}/><Summary label="Player appearances" value={s.total_players}/></div>
    </div>
    <div className="grid grid-cols-3 gap-2">{['DIRECTORS','VENUES','EVENTS'].map(name=><button key={name} onClick={()=>setView(name)} className={`min-h-[54px] rounded-2xl border font-black active:translate-y-1 ${view===name?'border-amber-300 bg-amber-300 text-black':'border-white/15 bg-zinc-900'}`}>{name[0]+name.slice(1).toLowerCase()}</button>)}</div>
    <form onSubmit={apply} className="grid gap-2 rounded-[24px] border border-white/10 bg-zinc-950 p-4 lg:grid-cols-[1fr_130px_155px_155px_auto]"><label className="flex items-center gap-2 rounded-xl bg-white/5 px-3"><Search size={17}/><input value={searchInput} onChange={e=>setSearchInput(e.target.value)} placeholder="Director, venue, city or event" className="w-full bg-transparent py-4 outline-none"/></label><select value={state} onChange={e=>setState(e.target.value)} className="rounded-xl bg-zinc-900 px-3"><option value="ALL">All locations</option>{(data?.states||[]).map((x:string)=><option key={x}>{x}</option>)}</select><input type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)} className="rounded-xl bg-zinc-900 px-3"/><input type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)} className="rounded-xl bg-zinc-900 px-3"/><button className="rounded-xl bg-amber-300 px-5 font-black text-black">Search</button></form>
    {error&&<div className="rounded-2xl border border-red-400/30 bg-red-950/30 p-4 text-red-200">{error}</div>}{loading?<div className="p-10 text-center text-zinc-500">Loading director records…</div>:<div className="grid gap-3 lg:grid-cols-2">{rows.map((row:any)=><Record key={row.director_key||row.venue_key||row.event_id} view={view} row={row}/>)}</div>}
  </section>;
}

function Record({view,row}:{view:string;row:any}){
  if(view==='EVENTS')return <article className="rounded-[24px] border border-white/10 bg-zinc-950 p-5"><div className="text-xs font-black uppercase tracking-wider text-amber-300">{row.event_date||'Date unknown'} · {row.event_time||'Time unknown'}</div><a href={`/?event_id=${row.event_id}`} className="mt-2 block text-xl font-black hover:text-amber-300">{row.event_name||`Event ${row.event_id}`}</a><div className="mt-3 space-y-2 text-sm text-zinc-400"><Line icon={<UsersRound/>}>{row.player_count??'—'} players · {row.team_count??'—'} teams</Line><Line icon={<Building2/>}>{row.venue_name}</Line><Line icon={<MapPin/>}>{location(row)}</Line><div className="font-bold text-white">Director: {row.director_name}</div>{row.director_email&&<a href={`mailto:${row.director_email}`} className="block text-sky-300">{row.director_email}</a>}</div></article>;
  if(view==='VENUES')return <article className="rounded-[24px] border border-white/10 bg-zinc-950 p-5"><div className="flex justify-between gap-3"><div><h3 className="text-xl font-black">{row.venue_name}</h3><div className="mt-1 text-sm text-zinc-500">{location(row)}</div></div><Building2 className="text-sky-300"/></div><div className="mt-4 grid grid-cols-3 gap-2"><Mini label="Events" value={row.event_count}/><Mini label="Avg players" value={row.average_players}/><Mini label="Directors" value={row.director_count}/></div><div className="mt-3 text-sm text-zinc-400">{row.director_names||'Director not captured'}</div></article>;
  return <article className="rounded-[24px] border border-white/10 bg-zinc-950 p-5"><h3 className="text-xl font-black">{row.display_name}</h3>{row.acl_player_id&&<div className="text-xs text-zinc-600">ACL {row.acl_player_id}</div>}<div className="mt-4 grid grid-cols-3 gap-2"><Mini label="Events" value={row.event_count}/><Mini label="Venues" value={row.venue_count}/><Mini label="Avg players" value={row.average_players}/></div><div className="mt-4 space-y-2">{row.email?<a href={`mailto:${row.email}`} className="flex items-center gap-2 text-sky-300"><Mail size={16}/>{row.email}</a>:null}{row.phone?<a href={`tel:${row.phone}`} className="flex items-center gap-2 text-emerald-300"><Phone size={16}/>{row.phone}</a>:null}</div><div className="mt-3 text-xs text-zinc-500">{row.venue_names||'No venue history'} · Latest {row.latest_event_date||'unknown'}</div></article>;
}
function Summary({label,value}:{label:string;value:any}){return <div className="rounded-2xl bg-white/[.04] p-3"><div className="text-2xl font-black">{Number(value||0).toLocaleString()}</div><div className="text-[9px] font-black uppercase tracking-wider text-zinc-500">{label}</div></div>}
function Mini({label,value}:{label:string;value:any}){return <div className="rounded-xl bg-white/[.04] p-3 text-center"><div className="text-lg font-black">{value??'—'}</div><div className="text-[9px] uppercase text-zinc-500">{label}</div></div>}
function Line({icon,children}:{icon:any;children:any}){return <div className="flex items-center gap-2">{<span className="[&>svg]:h-4 [&>svg]:w-4">{icon}</span>}{children}</div>}
function location(row:any){return [row.address,row.city,row.state,row.postal_code,row.country].filter(Boolean).join(', ')||'Location not captured'}
